const RESET_INPUT_FIELDS_VALUES_INITIALIZER_ACTION = 'RESET_INPUT_FIELDS_VALUES_INITIALIZER_ACTION';
const EDITABLE_TASK_OBJECT_ACTION = 'EDITABLE_TASK_OBJECT_ACTION';
const SWITCH_FOR_CLOSE_ALL_LISTS_FOR_TASKS_PROPERTIES_FILTER_ACTION = 'SWITCH_FOR_CLOSE_ALL_LISTS_FOR_TASKS_PROPERTIES_FILTER_ACTION';
const EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_TRUE = 'EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_TRUE';
const EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_FALSE = 'EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_FALSE';
const COUNTDOWN_FOR_LETTER_REQUEST = 'COUNTDOWN_FOR_LETTER_REQUEST';
const LAST_AUTHORIZATION = 'LAST_AUTHORIZATION';
const EVENT_FOR_PWA_INSTALLATION = 'EVENT_FOR_PWA_INSTALLATION';
const DEVICE_ON_THE_NETWORK_ACTION = 'DEVICE_ON_THE_NETWORK_ACTION';
const SELECT_TODAY_TASK_ID_ACTION = 'SELECT_TODAY_TASK_ID_ACTION';
const IS_FOCUS_ON_APP_ACTION = 'IS_FOCUS_ON_APP_ACTION';

export const resetInputFieldsValuesInitializerAction = {
    type: RESET_INPUT_FIELDS_VALUES_INITIALIZER_ACTION,
};

export const editableTaskObjectAction = {
    type: EDITABLE_TASK_OBJECT_ACTION,
};

export const switchForCloseAllListsForTasksPropertiesFilterAction = {
    type: SWITCH_FOR_CLOSE_ALL_LISTS_FOR_TASKS_PROPERTIES_FILTER_ACTION,
};

export const emailVerificationConfirmationWaitingIsTrue = {
    type: EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_TRUE,
};

export const emailVerificationConfirmationWaitingIsFalse = {
    type: EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_FALSE,
};

export const countdownForLetterRequest = {
    type: COUNTDOWN_FOR_LETTER_REQUEST,
};

export const lastAuthorization = {
    type: LAST_AUTHORIZATION,
};

export const eventForPWAInstallation = {
    type: EVENT_FOR_PWA_INSTALLATION,
};

export const deviceOnTheNetworkAction = {
    type: DEVICE_ON_THE_NETWORK_ACTION,
};

export const selectTodayTaskIDAction = {
    type: SELECT_TODAY_TASK_ID_ACTION,
};

export const isFocusOnAppAction = {
    type: IS_FOCUS_ON_APP_ACTION,
};
