const RESET_INPUT_FIELDS_VALUES_INITIALIZER_ACTION = 'RESET_INPUT_FIELDS_VALUES_INITIALIZER_ACTION';
const EDITABLE_TASK_OBJECT_ACTION = 'EDITABLE_TASK_OBJECT_ACTION';

export const resetInputFieldsValuesInitializerAction = {
    type: RESET_INPUT_FIELDS_VALUES_INITIALIZER_ACTION,
};

export const editableTaskObjectAction = {
    type: EDITABLE_TASK_OBJECT_ACTION,
};
