const RESET_INPUT_FIELDS_VALUES_INITIALIZER_ACTION = 'RESET_INPUT_FIELDS_VALUES_INITIALIZER_ACTION';

export const resetInputFieldsValuesInitializerAction = {
    type: RESET_INPUT_FIELDS_VALUES_INITIALIZER_ACTION,
};
